plugins {
    id 'com.android.application'
}

android {
    namespace 'com.saeid.artgallery'
    compileSdk 35

    defaultConfig {
        applicationId "app.rangingallery.mobile"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "4.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'androidx.biometric:biometric:1.1.0'
}
