plugins {
    id 'com.android.application'
}

android {
    namespace 'com.saeid.artgallery'
    compileSdk 35

    defaultConfig {
        applicationId "com.saeid.rangingallery"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "3.4"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
